import { Prisma } from "@prisma/client";

export const seedMovies: Prisma.MovieCreateInput[] = [
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    thumbnail: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    category: "Action",
    matchRate: 98,
    year: 2008,
    duration: 152,
    views: 1250000,
    ageRating: "R",
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    category: "Sci-Fi",
    matchRate: 88,
    year: 2010,
    duration: 148,
    views: 890000,
    ageRating: "PG-13",
  },
  {
    title: "Interstellar",
    description: "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    category: "Sci-Fi",
    matchRate: 95,
    year: 2014,
    duration: 169,
    views: 950000,
    ageRating: "PG-13",
  },
  {
    title: "The Godfather",
    description: "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=UaVTIH8mujA",
    category: "Drama",
    matchRate: 99,
    year: 1972,
    duration: 175,
    views: 2000000,
    ageRating: "R",
  },
  {
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
    category: "Animation",
    matchRate: 97,
    year: 2001,
    duration: 125,
    views: 620000,
    ageRating: "PG",
  },
  {
    title: "La La Land",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    category: "Romance",
    matchRate: 85,
    year: 2016,
    duration: 128,
    views: 450000,
    ageRating: "PG-13",
  },
  {
    title: "Knives Out",
    description: "A detective investigates the death of the patriarch of an eccentric, combative family.",
    thumbnail: "https://images.unsplash.com/photo-1585647347483-22b66260dfff?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
    category: "Comedy",
    matchRate: 92,
    year: 2019,
    duration: 130,
    views: 510000,
    ageRating: "PG-13",
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    thumbnail: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    category: "Thriller",
    matchRate: 96,
    year: 2019,
    duration: 132,
    views: 780000,
    ageRating: "R",
  },
  {
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    thumbnail: "https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=s7EgWkyY_lU",
    category: "Drama",
    matchRate: 94,
    year: 1994,
    duration: 154,
    views: 1100000,
    ageRating: "R",
  },
  {
    title: "The Matrix",
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    category: "Sci-Fi",
    matchRate: 95,
    year: 1999,
    duration: 136,
    views: 1300000,
    ageRating: "R",
  },
  {
    title: "Avengers: Endgame",
    description: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions.",
    thumbnail: "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    category: "Action",
    matchRate: 96,
    year: 2019,
    duration: 181,
    views: 3500000,
    ageRating: "PG-13",
  },
  {
    title: "Titanic",
    description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=CHekzSiZ47I",
    category: "Romance",
    matchRate: 89,
    year: 1997,
    duration: 194,
    views: 2400000,
    ageRating: "PG-13",
  },
  {
    title: "Jurassic Park",
    description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    thumbnail: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=QWBK657U9q4",
    category: "Adventure",
    matchRate: 91,
    year: 1993,
    duration: 127,
    views: 1800000,
    ageRating: "PG-13",
  },
  {
    title: "The Shawshank Redemption",
    description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    thumbnail: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=PLl99DlL6b4",
    category: "Drama",
    matchRate: 98,
    year: 1994,
    duration: 142,
    views: 2100000,
    ageRating: "R",
  },
  {
    title: "Gladiator",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    thumbnail: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=P5ieIbInFpg",
    category: "Action",
    matchRate: 93,
    year: 2000,
    duration: 155,
    views: 1400000,
    ageRating: "R",
  },
  {
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    thumbnail: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=7d_jQyGLDVc",
    category: "Music",
    matchRate: 92,
    year: 2014,
    duration: 106,
    views: 580000,
    ageRating: "R",
  },
  {
    title: "The Lion King",
    description: "A young lion prince is cast out of his pride by his cruel uncle, who claims he caused his father's death. While the uncle rules with an iron paw, the prince grows up beyond the Savannah.",
    thumbnail: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=lFzVJEksoDY",
    category: "Animation",
    matchRate: 95,
    year: 1994,
    duration: 88,
    views: 1900000,
    ageRating: "G",
  },
  {
    title: "Your Name",
    description: "Two strangers find themselves linked in a bizarre way. When a connection is formed, will distance be the only thing to keep them apart?",
    thumbnail: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=s0wTdCGKrJY",
    category: "Animation",
    matchRate: 96,
    year: 2016,
    duration: 106,
    views: 750000,
    ageRating: "PG",
  },
  {
    title: "Coco",
    description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=Ga6RYejoS1I",
    category: "Animation",
    matchRate: 94,
    year: 2017,
    duration: 105,
    views: 920000,
    ageRating: "PG",
  },
  {
    title: "Pee Mak",
    description: "After serving in a brutal war, Mak returns home to his beautiful wife Nak and four military comrades, only to find rumors that Nak has actually died and is now a ghost.",
    thumbnail: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=5Vz5Y-yK_U0",
    category: "Comedy",
    matchRate: 97,
    year: 2013,
    duration: 115,
    views: 1500000,
    ageRating: "PG-13",
  },
  {
    title: "Bad Genius",
    description: "Lynn, a genius high school student who makes money by cheating on tests, receives a new task that leads her to Sydney, Australia to pull off an international exams heist.",
    thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=CLHe8J_SNDc",
    category: "Thriller",
    matchRate: 96,
    year: 2017,
    duration: 130,
    views: 990000,
    ageRating: "PG-13",
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    description: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    thumbnail: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=g4Hbz2yLXGE",
    category: "Animation",
    matchRate: 95,
    year: 2018,
    duration: 117,
    views: 1400000,
    ageRating: "PG",
  },
  {
    title: "Dune",
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir is troubled by visions of a dark future.",
    thumbnail: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=n9DwoQ7HWvI",
    category: "Sci-Fi",
    matchRate: 91,
    year: 2021,
    duration: 155,
    views: 1200000,
    ageRating: "PG-13",
  },
  {
    title: "Mad Max: Fury Road",
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    thumbnail: "https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
    category: "Action",
    matchRate: 94,
    year: 2015,
    duration: 120,
    views: 1100000,
    ageRating: "R",
  },
  {
    title: "Get Out",
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point.",
    thumbnail: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=sRfnebToHE4",
    category: "Thriller",
    matchRate: 92,
    year: 2017,
    duration: 104,
    views: 890000,
    ageRating: "R",
  },
  {
    title: "The Conjuring",
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o",
    category: "Horror",
    matchRate: 93,
    year: 2013,
    duration: 112,
    views: 1050000,
    ageRating: "R",
  },
  {
    title: "A Quiet Place",
    description: "A family struggles for survival in a world where most humans have been killed by blind but noise-sensitive creatures. They must live in silence to survive.",
    thumbnail: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=WR7cc5t7tv8",
    category: "Horror",
    matchRate: 88,
    year: 2018,
    duration: 90,
    views: 780000,
    ageRating: "PG-13",
  },
  {
    title: "Black Panther",
    description: "T'Challa, heir to the hidden and advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    category: "Action",
    matchRate: 91,
    year: 2018,
    duration: 134,
    views: 1700000,
    ageRating: "PG-13",
  },
  {
    title: "Bohemian Rhapsody",
    description: "The story of the legendary British rock band Queen and their lead singer Freddie Mercury, leading up to their famous performance at Live Aid in 1985.",
    thumbnail: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=mP0VHJYFO98",
    category: "Biography",
    matchRate: 87,
    year: 2018,
    duration: 134,
    views: 940000,
    ageRating: "PG-13",
  },
  {
    title: "The Social Network",
    description: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out.",
    thumbnail: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=lB95KLKe0x8",
    category: "Biography",
    matchRate: 93,
    year: 2010,
    duration: 120,
    views: 820000,
    ageRating: "PG-13",
  },
  {
    title: "The Truman Show",
    description: "An insurance salesman discovers his whole life is actually a reality TV show broadcast to the entire world, prompting him to escape his artificial world.",
    thumbnail: "https://images.unsplash.com/photo-1601042879364-f3947d3f9c16?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=dlnmQbPGuls",
    category: "Comedy",
    matchRate: 95,
    year: 1998,
    duration: 103,
    views: 740000,
    ageRating: "PG",
  },
  {
    title: "Forrest Gump",
    description: "The history of the United States from the 1950s to the 1970s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
    thumbnail: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    category: "Drama",
    matchRate: 96,
    year: 1994,
    duration: 142,
    views: 1800000,
    ageRating: "PG-13",
  },
  {
    title: "Spider-Man: No Way Home",
    description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    thumbnail: "https://images.unsplash.com/photo-1634828221818-503587f33d02?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    category: "Action",
    matchRate: 94,
    year: 2021,
    duration: 148,
    views: 2200000,
    ageRating: "PG-13",
  },
  {
    title: "Ford v Ferrari",
    description: "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
    thumbnail: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=I3h9Z69mI_A",
    category: "Sport",
    matchRate: 93,
    year: 2019,
    duration: 152,
    views: 650000,
    ageRating: "PG-13",
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader across the galaxy.",
    thumbnail: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
    category: "Sci-Fi",
    matchRate: 97,
    year: 1980,
    duration: 124,
    views: 1500000,
    ageRating: "PG",
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    thumbnail: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=V75dMMBt2Ac",
    category: "Fantasy",
    matchRate: 96,
    year: 2001,
    duration: 178,
    views: 1800000,
    ageRating: "PG-13",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    description: "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
    thumbnail: "https://images.unsplash.com/photo-1510172951991-856a654063f9?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=VyHV0BRZYy4",
    category: "Fantasy",
    matchRate: 92,
    year: 2001,
    duration: 152,
    views: 2000000,
    ageRating: "PG",
  },
  {
    title: "The Silence of the Lambs",
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    thumbnail: "https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
    category: "Thriller",
    matchRate: 95,
    year: 1991,
    duration: 118,
    views: 1100000,
    ageRating: "R",
  },
  {
    title: "Django Unchained",
    description: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    thumbnail: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80",
    youtubeUrl: "https://www.youtube.com/watch?v=0fUCuvNlOCg",
    category: "Western",
    matchRate: 94,
    year: 2012,
    duration: 165,
    views: 870000,
    ageRating: "R",
  }
];
